# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-07-20 12:35
from __future__ import unicode_literals

from django.db import migrations, models
import fontawesome.fields
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicemodel',
            name='icon',
            field=fontawesome.fields.IconField(blank=True, default='Default service', max_length=60),
        ),
        migrations.AlterField(
            model_name='aboutmodel',
            name='description',
            field=tinymce.models.HTMLField(default='Default service', verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='aboutmodel',
            name='img',
            field=models.FileField(blank=True, default='Default service', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='aboutmodel',
            name='title',
            field=models.CharField(default='Default service', max_length=100),
        ),
        migrations.AlterField(
            model_name='servicemodel',
            name='service_desc',
            field=tinymce.models.HTMLField(default='Default service', verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='servicemodel',
            name='service_title',
            field=models.CharField(default='Default service', max_length=100),
        ),
    ]
